package cofrinho;

public enum EnumCombinations {
  // region A
  ARS_BRL(EnumCoins.descriptionFromCombinations(EnumCoins.ARS, EnumCoins.BRL)),
  AED_USD(EnumCoins.descriptionFromCombinations(EnumCoins.AED, EnumCoins.USD)),
  ARS_USD(EnumCoins.descriptionFromCombinations(EnumCoins.ARS, EnumCoins.USD)),
  AUD_BRL(EnumCoins.descriptionFromCombinations(EnumCoins.AUD, EnumCoins.BRL)),
  AUD_USD(EnumCoins.descriptionFromCombinations(EnumCoins.AUD, EnumCoins.USD)),
  ARS_EUR(EnumCoins.descriptionFromCombinations(EnumCoins.ARS, EnumCoins.EUR)),
  AUD_EUR(EnumCoins.descriptionFromCombinations(EnumCoins.AUD, EnumCoins.EUR)),
  AED_BRL(EnumCoins.descriptionFromCombinations(EnumCoins.AED, EnumCoins.BRL)),
  AFN_USD(EnumCoins.descriptionFromCombinations(EnumCoins.AFN, EnumCoins.USD)),
  //endregion
  //region B
  BOB_BRL(EnumCoins.descriptionFromCombinations(EnumCoins.BOB, EnumCoins.BRL)),
  BHD_EUR(EnumCoins.descriptionFromCombinations(EnumCoins.BHD, EnumCoins.EUR)),
  RUB_BRL(EnumCoins.descriptionFromCombinations(EnumCoins.RUB, EnumCoins.BRL)),
  BOB_USD(EnumCoins.descriptionFromCombinations(EnumCoins.BOB, EnumCoins.USD)),
  BTC_BRL(EnumCoins.descriptionFromCombinations(EnumCoins.BTC, EnumCoins.BRL)),
  BTC_USD(EnumCoins.descriptionFromCombinations(EnumCoins.BTC, EnumCoins.USD)),
  BRL_USD(EnumCoins.descriptionFromCombinations(EnumCoins.BRL, EnumCoins.USD)),
  BRL_EUR(EnumCoins.descriptionFromCombinations(EnumCoins.BRL, EnumCoins.EUR)),
  BTC_EUR(EnumCoins.descriptionFromCombinations(EnumCoins.BTC, EnumCoins.EUR)),
  BYN_USD(EnumCoins.descriptionFromCombinations(EnumCoins.BYN, EnumCoins.USD)),
  BRL_ARS(EnumCoins.descriptionFromCombinations(EnumCoins.BRL, EnumCoins.ARS)),
  BRL_AUD(EnumCoins.descriptionFromCombinations(EnumCoins.BRL, EnumCoins.AUD)),
  BRL_CAD(EnumCoins.descriptionFromCombinations(EnumCoins.BRL, EnumCoins.CAD)),
  BRL_CHF(EnumCoins.descriptionFromCombinations(EnumCoins.BRL, EnumCoins.CHF)),
  BRL_CLP(EnumCoins.descriptionFromCombinations(EnumCoins.BRL, EnumCoins.CLP)),
  BRL_DKK(EnumCoins.descriptionFromCombinations(EnumCoins.BRL, EnumCoins.DKK)),
  BRL_HKD(EnumCoins.descriptionFromCombinations(EnumCoins.BRL, EnumCoins.HKD)),
  BRL_JPY(EnumCoins.descriptionFromCombinations(EnumCoins.BRL, EnumCoins.JPY)),
  BRL_MXN(EnumCoins.descriptionFromCombinations(EnumCoins.BRL, EnumCoins.MXN)),
  BRL_SGD(EnumCoins.descriptionFromCombinations(EnumCoins.BRL, EnumCoins.SGD)),
  BRL_AED(EnumCoins.descriptionFromCombinations(EnumCoins.BRL, EnumCoins.AED)),
  BRL_BBD(EnumCoins.descriptionFromCombinations(EnumCoins.BRL, EnumCoins.BBD)),
  BRL_BHD(EnumCoins.descriptionFromCombinations(EnumCoins.BRL, EnumCoins.BHD)),
  BRL_CNY(EnumCoins.descriptionFromCombinations(EnumCoins.BRL, EnumCoins.CNY)),
  BRL_CZK(EnumCoins.descriptionFromCombinations(EnumCoins.BRL, EnumCoins.CZK)),
  BRL_EGP(EnumCoins.descriptionFromCombinations(EnumCoins.BRL, EnumCoins.EGP)),
  BRL_GBP(EnumCoins.descriptionFromCombinations(EnumCoins.BRL, EnumCoins.GBP)),
  BRL_HUF(EnumCoins.descriptionFromCombinations(EnumCoins.BRL, EnumCoins.HUF)),
  BRL_IDR(EnumCoins.descriptionFromCombinations(EnumCoins.BRL, EnumCoins.IDR)),
  BRL_ILS(EnumCoins.descriptionFromCombinations(EnumCoins.BRL, EnumCoins.ILS)),
  BRL_INR(EnumCoins.descriptionFromCombinations(EnumCoins.BRL, EnumCoins.INR)),
  BRL_ISK(EnumCoins.descriptionFromCombinations(EnumCoins.BRL, EnumCoins.ISK)),
  BRL_JMD(EnumCoins.descriptionFromCombinations(EnumCoins.BRL, EnumCoins.JMD)),
  BRL_JOD(EnumCoins.descriptionFromCombinations(EnumCoins.BRL, EnumCoins.JOD)),
  BRL_KES(EnumCoins.descriptionFromCombinations(EnumCoins.BRL, EnumCoins.KES)),
  BRL_KRW(EnumCoins.descriptionFromCombinations(EnumCoins.BRL, EnumCoins.KRW)),
  BRL_LBP(EnumCoins.descriptionFromCombinations(EnumCoins.BRL, EnumCoins.LBP)),
  BRL_LKR(EnumCoins.descriptionFromCombinations(EnumCoins.BRL, EnumCoins.LKR)),
  BRL_MAD(EnumCoins.descriptionFromCombinations(EnumCoins.BRL, EnumCoins.MAD)),
  BRL_MYR(EnumCoins.descriptionFromCombinations(EnumCoins.BRL, EnumCoins.MYR)),
  BRL_NAD(EnumCoins.descriptionFromCombinations(EnumCoins.BRL, EnumCoins.NAD)),
  BRL_NOK(EnumCoins.descriptionFromCombinations(EnumCoins.BRL, EnumCoins.NOK)),
  BRL_NPR(EnumCoins.descriptionFromCombinations(EnumCoins.BRL, EnumCoins.NPR)),
  BRL_NZD(EnumCoins.descriptionFromCombinations(EnumCoins.BRL, EnumCoins.NZD)),
  BRL_OMR(EnumCoins.descriptionFromCombinations(EnumCoins.BRL, EnumCoins.OMR)),
  BRL_PAB(EnumCoins.descriptionFromCombinations(EnumCoins.BRL, EnumCoins.PAB)),
  BRL_PHP(EnumCoins.descriptionFromCombinations(EnumCoins.BRL, EnumCoins.PHP)),
  BRL_PKR(EnumCoins.descriptionFromCombinations(EnumCoins.BRL, EnumCoins.PKR)),
  BRL_PLN(EnumCoins.descriptionFromCombinations(EnumCoins.BRL, EnumCoins.PLN)),
  BRL_QAR(EnumCoins.descriptionFromCombinations(EnumCoins.BRL, EnumCoins.QAR)),
  BRL_RON(EnumCoins.descriptionFromCombinations(EnumCoins.BRL, EnumCoins.RON)),
  BRL_RUB(EnumCoins.descriptionFromCombinations(EnumCoins.BRL, EnumCoins.RUB)),
  BRL_SAR(EnumCoins.descriptionFromCombinations(EnumCoins.BRL, EnumCoins.SAR)),
  BRL_SEK(EnumCoins.descriptionFromCombinations(EnumCoins.BRL, EnumCoins.SEK)),
  BRL_THB(EnumCoins.descriptionFromCombinations(EnumCoins.BRL, EnumCoins.THB)),
  BRL_TRY(EnumCoins.descriptionFromCombinations(EnumCoins.BRL, EnumCoins.TRY)),
  BRL_VEF(EnumCoins.descriptionFromCombinations(EnumCoins.BRL, EnumCoins.VEF)),
  BRL_XAF(EnumCoins.descriptionFromCombinations(EnumCoins.BRL, EnumCoins.XAF)),
  BRL_XCD(EnumCoins.descriptionFromCombinations(EnumCoins.BRL, EnumCoins.XCD)),
  BRL_XOF(EnumCoins.descriptionFromCombinations(EnumCoins.BRL, EnumCoins.XOF)),
  BRL_ZAR(EnumCoins.descriptionFromCombinations(EnumCoins.BRL, EnumCoins.ZAR)),
  BRL_TWD(EnumCoins.descriptionFromCombinations(EnumCoins.BRL, EnumCoins.TWD)),
  BRL_PYG(EnumCoins.descriptionFromCombinations(EnumCoins.BRL, EnumCoins.PYG)),
  BRL_UYU(EnumCoins.descriptionFromCombinations(EnumCoins.BRL, EnumCoins.UYU)),
  BRL_COP(EnumCoins.descriptionFromCombinations(EnumCoins.BRL, EnumCoins.COP)),
  BRL_PEN(EnumCoins.descriptionFromCombinations(EnumCoins.BRL, EnumCoins.PEN)),
  BRL_BOB(EnumCoins.descriptionFromCombinations(EnumCoins.BRL, EnumCoins.BOB)),
  BYN_EUR(EnumCoins.descriptionFromCombinations(EnumCoins.BYN, EnumCoins.EUR)),
  //endregion
  // region C
  CAD_EUR(EnumCoins.descriptionFromCombinations(EnumCoins.CAD, EnumCoins.EUR)),
  CAD_USD(EnumCoins.descriptionFromCombinations(EnumCoins.CAD, EnumCoins.USD)),
  CAD_BRL(EnumCoins.descriptionFromCombinations(EnumCoins.CAD, EnumCoins.BRL)),
  CHF_BRL(EnumCoins.descriptionFromCombinations(EnumCoins.CHF, EnumCoins.BRL)),
  CNY_BRL(EnumCoins.descriptionFromCombinations(EnumCoins.CNY, EnumCoins.BRL)),
  CHF_USD(EnumCoins.descriptionFromCombinations(EnumCoins.CHF, EnumCoins.USD)),
  CNY_USD(EnumCoins.descriptionFromCombinations(EnumCoins.CNY, EnumCoins.USD)),
  COP_BRL(EnumCoins.descriptionFromCombinations(EnumCoins.COP, EnumCoins.BRL)),
  CNY_EUR(EnumCoins.descriptionFromCombinations(EnumCoins.CNY, EnumCoins.EUR)),
  CLP_BRL(EnumCoins.descriptionFromCombinations(EnumCoins.CLP, EnumCoins.BRL)),
  CHF_EUR(EnumCoins.descriptionFromCombinations(EnumCoins.CHF, EnumCoins.EUR)),
  CLP_USD(EnumCoins.descriptionFromCombinations(EnumCoins.CLP, EnumCoins.USD)),
  COP_USD(EnumCoins.descriptionFromCombinations(EnumCoins.COP, EnumCoins.USD)),
  //endregion
  // region D
  DKK_BRL(EnumCoins.descriptionFromCombinations(EnumCoins.DKK, EnumCoins.BRL)),
  DOGE_BRL(EnumCoins.descriptionFromCombinations(EnumCoins.DOGE, EnumCoins.BRL)),
  DKK_EUR(EnumCoins.descriptionFromCombinations(EnumCoins.DKK, EnumCoins.EUR)),
  DOGE_EUR(EnumCoins.descriptionFromCombinations(EnumCoins.DOGE, EnumCoins.EUR)),
  DOGE_USD(EnumCoins.descriptionFromCombinations(EnumCoins.DOGE, EnumCoins.USD)),
  DKK_USD(EnumCoins.descriptionFromCombinations(EnumCoins.DKK, EnumCoins.USD)),
  //endregion
  // region E
  EUR_BRL(EnumCoins.descriptionFromCombinations(EnumCoins.EUR, EnumCoins.BRL)),
  EGP_EUR(EnumCoins.descriptionFromCombinations(EnumCoins.EGP, EnumCoins.EUR)),
  EUR_GBP(EnumCoins.descriptionFromCombinations(EnumCoins.EUR, EnumCoins.GBP)),
  EGP_USD(EnumCoins.descriptionFromCombinations(EnumCoins.EGP, EnumCoins.USD)),
  ETH_BRL(EnumCoins.descriptionFromCombinations(EnumCoins.ETH, EnumCoins.BRL)),
  ETH_USD(EnumCoins.descriptionFromCombinations(EnumCoins.ETH, EnumCoins.USD)),
  ETH_EUR(EnumCoins.descriptionFromCombinations(EnumCoins.ETH, EnumCoins.EUR)),
  EUR_USD(EnumCoins.descriptionFromCombinations(EnumCoins.EUR, EnumCoins.USD)),
  EUR_JPY(EnumCoins.descriptionFromCombinations(EnumCoins.EUR, EnumCoins.JPY)),
  EUR_CHF(EnumCoins.descriptionFromCombinations(EnumCoins.EUR, EnumCoins.CHF)),
  EUR_AUD(EnumCoins.descriptionFromCombinations(EnumCoins.EUR, EnumCoins.AUD)),
  EUR_CAD(EnumCoins.descriptionFromCombinations(EnumCoins.EUR, EnumCoins.CAD)),
  EUR_NOK(EnumCoins.descriptionFromCombinations(EnumCoins.EUR, EnumCoins.NOK)),
  EUR_DKK(EnumCoins.descriptionFromCombinations(EnumCoins.EUR, EnumCoins.DKK)),
  EUR_PLN(EnumCoins.descriptionFromCombinations(EnumCoins.EUR, EnumCoins.PLN)),
  EUR_NZD(EnumCoins.descriptionFromCombinations(EnumCoins.EUR, EnumCoins.NZD)),
  EUR_SEK(EnumCoins.descriptionFromCombinations(EnumCoins.EUR, EnumCoins.SEK)),
  EUR_ILS(EnumCoins.descriptionFromCombinations(EnumCoins.EUR, EnumCoins.ILS)),
  EUR_TRY(EnumCoins.descriptionFromCombinations(EnumCoins.EUR, EnumCoins.TRY)),
  EUR_THB(EnumCoins.descriptionFromCombinations(EnumCoins.EUR, EnumCoins.THB)),
  EUR_ZAR(EnumCoins.descriptionFromCombinations(EnumCoins.EUR, EnumCoins.ZAR)),
  EUR_MXN(EnumCoins.descriptionFromCombinations(EnumCoins.EUR, EnumCoins.MXN)),
  EUR_SGD(EnumCoins.descriptionFromCombinations(EnumCoins.EUR, EnumCoins.SGD)),
  EUR_HUF(EnumCoins.descriptionFromCombinations(EnumCoins.EUR, EnumCoins.HUF)),
  EUR_HKD(EnumCoins.descriptionFromCombinations(EnumCoins.EUR, EnumCoins.HKD)),
  EUR_CZK(EnumCoins.descriptionFromCombinations(EnumCoins.EUR, EnumCoins.CZK)),
  EUR_KRW(EnumCoins.descriptionFromCombinations(EnumCoins.EUR, EnumCoins.KRW)),
  EUR_AED(EnumCoins.descriptionFromCombinations(EnumCoins.EUR, EnumCoins.AED)),
  EUR_AFN(EnumCoins.descriptionFromCombinations(EnumCoins.EUR, EnumCoins.AFN)),
  EUR_ALL(EnumCoins.descriptionFromCombinations(EnumCoins.EUR, EnumCoins.ALL)),
  EUR_ANG(EnumCoins.descriptionFromCombinations(EnumCoins.EUR, EnumCoins.ANG)),
  EUR_ARS(EnumCoins.descriptionFromCombinations(EnumCoins.EUR, EnumCoins.ARS)),
  EUR_BAM(EnumCoins.descriptionFromCombinations(EnumCoins.EUR, EnumCoins.BAM)),
  EUR_BBD(EnumCoins.descriptionFromCombinations(EnumCoins.EUR, EnumCoins.BBD)),
  EUR_BDT(EnumCoins.descriptionFromCombinations(EnumCoins.EUR, EnumCoins.BDT)),
  EUR_BGN(EnumCoins.descriptionFromCombinations(EnumCoins.EUR, EnumCoins.BGN)),
  EUR_BHD(EnumCoins.descriptionFromCombinations(EnumCoins.EUR, EnumCoins.BHD)),
  EUR_BIF(EnumCoins.descriptionFromCombinations(EnumCoins.EUR, EnumCoins.BIF)),
  EUR_BND(EnumCoins.descriptionFromCombinations(EnumCoins.EUR, EnumCoins.BND)),
  EUR_BOB(EnumCoins.descriptionFromCombinations(EnumCoins.EUR, EnumCoins.BOB)),
  EUR_BSD(EnumCoins.descriptionFromCombinations(EnumCoins.EUR, EnumCoins.BSD)),
  EUR_BWP(EnumCoins.descriptionFromCombinations(EnumCoins.EUR, EnumCoins.BWP)),
  EUR_BYN(EnumCoins.descriptionFromCombinations(EnumCoins.EUR, EnumCoins.BYN)),
  EUR_BZD(EnumCoins.descriptionFromCombinations(EnumCoins.EUR, EnumCoins.BZD)),
  EUR_CLP(EnumCoins.descriptionFromCombinations(EnumCoins.EUR, EnumCoins.CLP)),
  EUR_CNY(EnumCoins.descriptionFromCombinations(EnumCoins.EUR, EnumCoins.CNY)),
  EUR_COP(EnumCoins.descriptionFromCombinations(EnumCoins.EUR, EnumCoins.COP)),
  EUR_CRC(EnumCoins.descriptionFromCombinations(EnumCoins.EUR, EnumCoins.CRC)),
  EUR_CUP(EnumCoins.descriptionFromCombinations(EnumCoins.EUR, EnumCoins.CUP)),
  EUR_CVE(EnumCoins.descriptionFromCombinations(EnumCoins.EUR, EnumCoins.CVE)),
  EUR_DJF(EnumCoins.descriptionFromCombinations(EnumCoins.EUR, EnumCoins.DJF)),
  EUR_DOP(EnumCoins.descriptionFromCombinations(EnumCoins.EUR, EnumCoins.DOP)),
  EUR_DZD(EnumCoins.descriptionFromCombinations(EnumCoins.EUR, EnumCoins.DZD)),
  EUR_EGP(EnumCoins.descriptionFromCombinations(EnumCoins.EUR, EnumCoins.EGP)),
  EUR_ETB(EnumCoins.descriptionFromCombinations(EnumCoins.EUR, EnumCoins.ETB)),
  EUR_FJD(EnumCoins.descriptionFromCombinations(EnumCoins.EUR, EnumCoins.FJD)),
  EUR_GHS(EnumCoins.descriptionFromCombinations(EnumCoins.EUR, EnumCoins.GHS)),
  EUR_GMD(EnumCoins.descriptionFromCombinations(EnumCoins.EUR, EnumCoins.GMD)),
  EUR_GNF(EnumCoins.descriptionFromCombinations(EnumCoins.EUR, EnumCoins.GNF)),
  EUR_GTQ(EnumCoins.descriptionFromCombinations(EnumCoins.EUR, EnumCoins.GTQ)),
  EUR_HNL(EnumCoins.descriptionFromCombinations(EnumCoins.EUR, EnumCoins.HNL)),
  EUR_HRK(EnumCoins.descriptionFromCombinations(EnumCoins.EUR, EnumCoins.HRK)),
  EUR_HTG(EnumCoins.descriptionFromCombinations(EnumCoins.EUR, EnumCoins.HTG)),
  EUR_IDR(EnumCoins.descriptionFromCombinations(EnumCoins.EUR, EnumCoins.IDR)),
  EUR_INR(EnumCoins.descriptionFromCombinations(EnumCoins.EUR, EnumCoins.INR)),
  EUR_IQD(EnumCoins.descriptionFromCombinations(EnumCoins.EUR, EnumCoins.IQD)),
  EUR_IRR(EnumCoins.descriptionFromCombinations(EnumCoins.EUR, EnumCoins.IRR)),
  EUR_ISK(EnumCoins.descriptionFromCombinations(EnumCoins.EUR, EnumCoins.ISK)),
  EUR_JMD(EnumCoins.descriptionFromCombinations(EnumCoins.EUR, EnumCoins.JMD)),
  EUR_JOD(EnumCoins.descriptionFromCombinations(EnumCoins.EUR, EnumCoins.JOD)),
  EUR_KES(EnumCoins.descriptionFromCombinations(EnumCoins.EUR, EnumCoins.KES)),
  EUR_KHR(EnumCoins.descriptionFromCombinations(EnumCoins.EUR, EnumCoins.KHR)),
  EUR_KWD(EnumCoins.descriptionFromCombinations(EnumCoins.EUR, EnumCoins.KWD)),
  EUR_KYD(EnumCoins.descriptionFromCombinations(EnumCoins.EUR, EnumCoins.KYD)),
  EUR_KZT(EnumCoins.descriptionFromCombinations(EnumCoins.EUR, EnumCoins.KZT)),
  EUR_LAK(EnumCoins.descriptionFromCombinations(EnumCoins.EUR, EnumCoins.LAK)),
  EUR_LBP(EnumCoins.descriptionFromCombinations(EnumCoins.EUR, EnumCoins.LBP)),
  EUR_LKR(EnumCoins.descriptionFromCombinations(EnumCoins.EUR, EnumCoins.LKR)),
  EUR_LSL(EnumCoins.descriptionFromCombinations(EnumCoins.EUR, EnumCoins.LSL)),
  EUR_LYD(EnumCoins.descriptionFromCombinations(EnumCoins.EUR, EnumCoins.LYD)),
  EUR_MAD(EnumCoins.descriptionFromCombinations(EnumCoins.EUR, EnumCoins.MAD)),
  EUR_MDL(EnumCoins.descriptionFromCombinations(EnumCoins.EUR, EnumCoins.MDL)),
  EUR_MGA(EnumCoins.descriptionFromCombinations(EnumCoins.EUR, EnumCoins.MGA)),
  EUR_MKD(EnumCoins.descriptionFromCombinations(EnumCoins.EUR, EnumCoins.MKD)),
  EUR_MMK(EnumCoins.descriptionFromCombinations(EnumCoins.EUR, EnumCoins.MMK)),
  EUR_MOP(EnumCoins.descriptionFromCombinations(EnumCoins.EUR, EnumCoins.MOP)),
  EUR_MRO(EnumCoins.descriptionFromCombinations(EnumCoins.EUR, EnumCoins.MRO)),
  EUR_MUR(EnumCoins.descriptionFromCombinations(EnumCoins.EUR, EnumCoins.MUR)),
  EUR_MWK(EnumCoins.descriptionFromCombinations(EnumCoins.EUR, EnumCoins.MWK)),
  EUR_MYR(EnumCoins.descriptionFromCombinations(EnumCoins.EUR, EnumCoins.MYR)),
  EUR_NAD(EnumCoins.descriptionFromCombinations(EnumCoins.EUR, EnumCoins.NAD)),
  EUR_NGN(EnumCoins.descriptionFromCombinations(EnumCoins.EUR, EnumCoins.NGN)),
  EUR_NIO(EnumCoins.descriptionFromCombinations(EnumCoins.EUR, EnumCoins.NIO)),
  EUR_NPR(EnumCoins.descriptionFromCombinations(EnumCoins.EUR, EnumCoins.NPR)),
  EUR_OMR(EnumCoins.descriptionFromCombinations(EnumCoins.EUR, EnumCoins.OMR)),
  EUR_PAB(EnumCoins.descriptionFromCombinations(EnumCoins.EUR, EnumCoins.PAB)),
  EUR_PEN(EnumCoins.descriptionFromCombinations(EnumCoins.EUR, EnumCoins.PEN)),
  EUR_PGK(EnumCoins.descriptionFromCombinations(EnumCoins.EUR, EnumCoins.PGK)),
  EUR_PHP(EnumCoins.descriptionFromCombinations(EnumCoins.EUR, EnumCoins.PHP)),
  EUR_PKR(EnumCoins.descriptionFromCombinations(EnumCoins.EUR, EnumCoins.PKR)),
  EUR_PYG(EnumCoins.descriptionFromCombinations(EnumCoins.EUR, EnumCoins.PYG)),
  EUR_QAR(EnumCoins.descriptionFromCombinations(EnumCoins.EUR, EnumCoins.QAR)),
  EUR_RON(EnumCoins.descriptionFromCombinations(EnumCoins.EUR, EnumCoins.RON)),
  EUR_RSD(EnumCoins.descriptionFromCombinations(EnumCoins.EUR, EnumCoins.RSD)),
  EUR_RWF(EnumCoins.descriptionFromCombinations(EnumCoins.EUR, EnumCoins.RWF)),
  EUR_SAR(EnumCoins.descriptionFromCombinations(EnumCoins.EUR, EnumCoins.SAR)),
  EUR_SCR(EnumCoins.descriptionFromCombinations(EnumCoins.EUR, EnumCoins.SCR)),
  EUR_SDG(EnumCoins.descriptionFromCombinations(EnumCoins.EUR, EnumCoins.SDG)),
  AED_EUR(EnumCoins.descriptionFromCombinations(EnumCoins.EUR, EnumCoins.EUR)),
  EUR_SDR(EnumCoins.descriptionFromCombinations(EnumCoins.EUR, EnumCoins.SDR)),
  EUR_SOS(EnumCoins.descriptionFromCombinations(EnumCoins.EUR, EnumCoins.SOS)),
  EUR_STD(EnumCoins.descriptionFromCombinations(EnumCoins.EUR, EnumCoins.STD)),
  EUR_SVC(EnumCoins.descriptionFromCombinations(EnumCoins.EUR, EnumCoins.SVC)),
  EUR_SYP(EnumCoins.descriptionFromCombinations(EnumCoins.EUR, EnumCoins.SYP)),
  EUR_SZL(EnumCoins.descriptionFromCombinations(EnumCoins.EUR, EnumCoins.SZL)),
  EUR_TND(EnumCoins.descriptionFromCombinations(EnumCoins.EUR, EnumCoins.TND)),
  EUR_TTD(EnumCoins.descriptionFromCombinations(EnumCoins.EUR, EnumCoins.TTD)),
  EUR_TWD(EnumCoins.descriptionFromCombinations(EnumCoins.EUR, EnumCoins.TWD)),
  EUR_TZS(EnumCoins.descriptionFromCombinations(EnumCoins.EUR, EnumCoins.TZS)),
  EUR_UAH(EnumCoins.descriptionFromCombinations(EnumCoins.EUR, EnumCoins.UAH)),
  EUR_UGX(EnumCoins.descriptionFromCombinations(EnumCoins.EUR, EnumCoins.UGX)),
  EUR_UYU(EnumCoins.descriptionFromCombinations(EnumCoins.EUR, EnumCoins.UYU)),
  EUR_UZS(EnumCoins.descriptionFromCombinations(EnumCoins.EUR, EnumCoins.UZS)),
  EUR_VEF(EnumCoins.descriptionFromCombinations(EnumCoins.EUR, EnumCoins.VEF)),
  EUR_VND(EnumCoins.descriptionFromCombinations(EnumCoins.EUR, EnumCoins.VND)),
  EUR_XAF(EnumCoins.descriptionFromCombinations(EnumCoins.EUR, EnumCoins.XAF)),
  EUR_XOF(EnumCoins.descriptionFromCombinations(EnumCoins.EUR, EnumCoins.XOF)),
  EUR_XPF(EnumCoins.descriptionFromCombinations(EnumCoins.EUR, EnumCoins.XPF)),
  EUR_ZMK(EnumCoins.descriptionFromCombinations(EnumCoins.EUR, EnumCoins.ZMK)),
  EUR_XCD(EnumCoins.descriptionFromCombinations(EnumCoins.EUR, EnumCoins.XCD)),
  EUR_MZN(EnumCoins.descriptionFromCombinations(EnumCoins.EUR, EnumCoins.MZN)),
  EUR_AZN(EnumCoins.descriptionFromCombinations(EnumCoins.EUR, EnumCoins.AZN)),
  EUR_AMD(EnumCoins.descriptionFromCombinations(EnumCoins.EUR, EnumCoins.AMD)),
  EUR_TJS(EnumCoins.descriptionFromCombinations(EnumCoins.EUR, EnumCoins.TJS)),
  EUR_RUB(EnumCoins.descriptionFromCombinations(EnumCoins.EUR, EnumCoins.RUB)),
  EUR_GEL(EnumCoins.descriptionFromCombinations(EnumCoins.EUR, EnumCoins.GEL)),
  EUR_AOA(EnumCoins.descriptionFromCombinations(EnumCoins.EUR, EnumCoins.AOA)),
  //endregion
  // region F
  FJD_USD(EnumCoins.descriptionFromCombinations(EnumCoins.FJD, EnumCoins.USD)),
  //endregion
  // region G
  GBP_BRL(EnumCoins.descriptionFromCombinations(EnumCoins.GBP, EnumCoins.BRL)),
  GEL_EUR(EnumCoins.descriptionFromCombinations(EnumCoins.GEL, EnumCoins.EUR)),
  GHS_EUR(EnumCoins.descriptionFromCombinations(EnumCoins.GHS, EnumCoins.EUR)),
  GBP_EUR(EnumCoins.descriptionFromCombinations(EnumCoins.GBP, EnumCoins.EUR)),
  GBP_USD(EnumCoins.descriptionFromCombinations(EnumCoins.GBP, EnumCoins.USD)),
  GHS_USD(EnumCoins.descriptionFromCombinations(EnumCoins.GHS, EnumCoins.USD)),
  //endregion
  // region H
  HKD_BRL(EnumCoins.descriptionFromCombinations(EnumCoins.HKD, EnumCoins.BRL)),
  HKD_EUR(EnumCoins.descriptionFromCombinations(EnumCoins.HKD, EnumCoins.EUR)),
  HKD_USD(EnumCoins.descriptionFromCombinations(EnumCoins.HKD, EnumCoins.USD)),
  HUF_EUR(EnumCoins.descriptionFromCombinations(EnumCoins.HUF, EnumCoins.EUR)),
  HUF_USD(EnumCoins.descriptionFromCombinations(EnumCoins.HUF, EnumCoins.USD)),
  //endregion
  // region I
  IDR_EUR(EnumCoins.descriptionFromCombinations(EnumCoins.IDR, EnumCoins.EUR)),
  IDR_USD(EnumCoins.descriptionFromCombinations(EnumCoins.IDR, EnumCoins.USD)),
  ILS_BRL(EnumCoins.descriptionFromCombinations(EnumCoins.ILS, EnumCoins.BRL)),
  ILS_USD(EnumCoins.descriptionFromCombinations(EnumCoins.ILS, EnumCoins.USD)),
  ILS_EUR(EnumCoins.descriptionFromCombinations(EnumCoins.ILS, EnumCoins.EUR)),
  INR_EUR(EnumCoins.descriptionFromCombinations(EnumCoins.INR, EnumCoins.EUR)),
  INR_USD(EnumCoins.descriptionFromCombinations(EnumCoins.INR, EnumCoins.USD)),
  INR_BRL(EnumCoins.descriptionFromCombinations(EnumCoins.INR, EnumCoins.BRL)),
  IRR_USD(EnumCoins.descriptionFromCombinations(EnumCoins.IRR, EnumCoins.USD)),
  IQD_USD(EnumCoins.descriptionFromCombinations(EnumCoins.IQD, EnumCoins.USD)),
  //endregion
  // region J
  JOD_EUR(EnumCoins.descriptionFromCombinations(EnumCoins.JOD, EnumCoins.EUR)),
  JOD_USD(EnumCoins.descriptionFromCombinations(EnumCoins.JOD, EnumCoins.USD)),
  JPY_USD(EnumCoins.descriptionFromCombinations(EnumCoins.JPY, EnumCoins.USD)),
  JPY_BRL(EnumCoins.descriptionFromCombinations(EnumCoins.JPY, EnumCoins.BRL)),
  JPY_EUR(EnumCoins.descriptionFromCombinations(EnumCoins.JPY, EnumCoins.EUR)),
  //endregion
  // region K
  KYD_USD(EnumCoins.descriptionFromCombinations(EnumCoins.KYD, EnumCoins.USD)),
  KRW_EUR(EnumCoins.descriptionFromCombinations(EnumCoins.KRW, EnumCoins.EUR)),
  KRW_USD(EnumCoins.descriptionFromCombinations(EnumCoins.KRW, EnumCoins.USD)),
  KWD_EUR(EnumCoins.descriptionFromCombinations(EnumCoins.KWD, EnumCoins.EUR)),
  KWD_USD(EnumCoins.descriptionFromCombinations(EnumCoins.KWD, EnumCoins.USD)),
  //endregion
  // region L
  LTC_BRL(EnumCoins.descriptionFromCombinations(EnumCoins.LTC, EnumCoins.BRL)),
  LTC_USD(EnumCoins.descriptionFromCombinations(EnumCoins.LTC, EnumCoins.USD)),
  LTC_EUR(EnumCoins.descriptionFromCombinations(EnumCoins.LTC, EnumCoins.EUR)),
  //endregion
  // region M
  MAD_EUR(EnumCoins.descriptionFromCombinations(EnumCoins.MAD, EnumCoins.EUR)),
  MXN_BRL(EnumCoins.descriptionFromCombinations(EnumCoins.MXN, EnumCoins.BRL)),
  MXN_EUR(EnumCoins.descriptionFromCombinations(EnumCoins.MXN, EnumCoins.EUR)),
  MXN_USD(EnumCoins.descriptionFromCombinations(EnumCoins.MXN, EnumCoins.USD)),
  MYR_USD(EnumCoins.descriptionFromCombinations(EnumCoins.MYR, EnumCoins.USD)),
  //endregion
  // region N
  NIO_USD(EnumCoins.descriptionFromCombinations(EnumCoins.BOB, EnumCoins.USD)),
  NOK_BRL(EnumCoins.descriptionFromCombinations(EnumCoins.NOK, EnumCoins.BRL)),
  NOK_EUR(EnumCoins.descriptionFromCombinations(EnumCoins.NOK, EnumCoins.EUR)),
  NOK_USD(EnumCoins.descriptionFromCombinations(EnumCoins.NOK, EnumCoins.USD)),
  NZD_EUR(EnumCoins.descriptionFromCombinations(EnumCoins.NZD, EnumCoins.EUR)),
  NZD_BRL(EnumCoins.descriptionFromCombinations(EnumCoins.NZD, EnumCoins.BRL)),
  NZD_USD(EnumCoins.descriptionFromCombinations(EnumCoins.NZD, EnumCoins.USD)),
  //endregion
  // region P
  PEN_BRL(EnumCoins.descriptionFromCombinations(EnumCoins.PEN, EnumCoins.BRL)),
  PYG_BRL(EnumCoins.descriptionFromCombinations(EnumCoins.PYG, EnumCoins.BRL)),
  PLN_BRL(EnumCoins.descriptionFromCombinations(EnumCoins.PLN, EnumCoins.BRL)),
  PLN_EUR(EnumCoins.descriptionFromCombinations(EnumCoins.PLN, EnumCoins.EUR)),
  PEN_EUR(EnumCoins.descriptionFromCombinations(EnumCoins.PEN, EnumCoins.EUR)),
  PLN_USD(EnumCoins.descriptionFromCombinations(EnumCoins.PLN, EnumCoins.USD)),
  PEN_USD(EnumCoins.descriptionFromCombinations(EnumCoins.PEN, EnumCoins.USD)),
  PHP_USD(EnumCoins.descriptionFromCombinations(EnumCoins.PHP, EnumCoins.USD)),
  PYG_USD(EnumCoins.descriptionFromCombinations(EnumCoins.PYG, EnumCoins.USD)),
  //endregion
  // region R
  RUB_EUR(EnumCoins.descriptionFromCombinations(EnumCoins.RUB, EnumCoins.EUR)),
  RUB_USD(EnumCoins.descriptionFromCombinations(EnumCoins.RUB, EnumCoins.USD)),
  //endregion
  // region S
  SAR_BRL(EnumCoins.descriptionFromCombinations(EnumCoins.SAR, EnumCoins.BRL)),
  SAR_EUR(EnumCoins.descriptionFromCombinations(EnumCoins.SAR, EnumCoins.EUR)),
  SAR_USD(EnumCoins.descriptionFromCombinations(EnumCoins.SAR, EnumCoins.USD)),
  SEK_BRL(EnumCoins.descriptionFromCombinations(EnumCoins.SEK, EnumCoins.BRL)),
  SEK_USD(EnumCoins.descriptionFromCombinations(EnumCoins.SEK, EnumCoins.USD)),
  SGD_BRL(EnumCoins.descriptionFromCombinations(EnumCoins.SGD, EnumCoins.BRL)),
  SEK_EUR(EnumCoins.descriptionFromCombinations(EnumCoins.SEK, EnumCoins.EUR)),
  SGD_EUR(EnumCoins.descriptionFromCombinations(EnumCoins.SGD, EnumCoins.EUR)),
  SGD_USD(EnumCoins.descriptionFromCombinations(EnumCoins.SGD, EnumCoins.USD)),
  SYP_USD(EnumCoins.descriptionFromCombinations(EnumCoins.SYP, EnumCoins.USD)),
  //endregion
  // region T
  THB_BRL(EnumCoins.descriptionFromCombinations(EnumCoins.THB, EnumCoins.BRL)),
  THB_USD(EnumCoins.descriptionFromCombinations(EnumCoins.THB, EnumCoins.USD)),
  TRY_USD(EnumCoins.descriptionFromCombinations(EnumCoins.TRY, EnumCoins.USD)),
  TRY_BRL(EnumCoins.descriptionFromCombinations(EnumCoins.TRY, EnumCoins.BRL)),
  TRY_EUR(EnumCoins.descriptionFromCombinations(EnumCoins.TRY, EnumCoins.EUR)),
  TWD_USD(EnumCoins.descriptionFromCombinations(EnumCoins.TWD, EnumCoins.USD)),
  TWD_BRL(EnumCoins.descriptionFromCombinations(EnumCoins.TWD, EnumCoins.BRL)),
  TWD_EUR(EnumCoins.descriptionFromCombinations(EnumCoins.TWD, EnumCoins.EUR)),

  //endregion
  // region U
  USD_BRL(EnumCoins.descriptionFromCombinations(EnumCoins.USD, EnumCoins.BRL)),
  USD_BRLT(EnumCoins.descriptionFromCombinations(EnumCoins.USD, EnumCoins.BRLT)),
  UYU_BRL(EnumCoins.descriptionFromCombinations(EnumCoins.UYU, EnumCoins.BRL)),
  UAH_USD(EnumCoins.descriptionFromCombinations(EnumCoins.UAH, EnumCoins.USD)),
  USD_NGNI(EnumCoins.descriptionFromCombinations(EnumCoins.USD, EnumCoins.NGNI)),
  USD_ZWL(EnumCoins.descriptionFromCombinations(EnumCoins.USD, EnumCoins.ZWL)),
  UYU_USD(EnumCoins.descriptionFromCombinations(EnumCoins.UYU, EnumCoins.USD)),
  USD_CAD(EnumCoins.descriptionFromCombinations(EnumCoins.USD, EnumCoins.CAD)),
  USD_JPY(EnumCoins.descriptionFromCombinations(EnumCoins.USD, EnumCoins.JPY)),
  USD_CHF(EnumCoins.descriptionFromCombinations(EnumCoins.USD, EnumCoins.CHF)),
  USD_MZN(EnumCoins.descriptionFromCombinations(EnumCoins.USD, EnumCoins.MZN)),
  USD_RUB(EnumCoins.descriptionFromCombinations(EnumCoins.USD, EnumCoins.RUB)),
  USD_TRY(EnumCoins.descriptionFromCombinations(EnumCoins.USD, EnumCoins.TRY)),
  USD_MXN(EnumCoins.descriptionFromCombinations(EnumCoins.USD, EnumCoins.MXN)),
  USD_PLN(EnumCoins.descriptionFromCombinations(EnumCoins.USD, EnumCoins.PLN)),
  USD_SEK(EnumCoins.descriptionFromCombinations(EnumCoins.USD, EnumCoins.SEK)),
  USD_SGD(EnumCoins.descriptionFromCombinations(EnumCoins.USD, EnumCoins.SGD)),
  USD_ZAR(EnumCoins.descriptionFromCombinations(EnumCoins.USD, EnumCoins.ZAR)),
  USD_DKK(EnumCoins.descriptionFromCombinations(EnumCoins.USD, EnumCoins.DKK)),
  USD_NOK(EnumCoins.descriptionFromCombinations(EnumCoins.USD, EnumCoins.NOK)),
  USD_ILS(EnumCoins.descriptionFromCombinations(EnumCoins.USD, EnumCoins.ILS)),
  USD_HUF(EnumCoins.descriptionFromCombinations(EnumCoins.USD, EnumCoins.HUF)),
  USD_CZK(EnumCoins.descriptionFromCombinations(EnumCoins.USD, EnumCoins.CZK)),
  USD_THB(EnumCoins.descriptionFromCombinations(EnumCoins.USD, EnumCoins.THB)),
  USD_AED(EnumCoins.descriptionFromCombinations(EnumCoins.USD, EnumCoins.AED)),
  USD_JOD(EnumCoins.descriptionFromCombinations(EnumCoins.USD, EnumCoins.JOD)),
  USD_KWD(EnumCoins.descriptionFromCombinations(EnumCoins.USD, EnumCoins.KWD)),
  USD_HKD(EnumCoins.descriptionFromCombinations(EnumCoins.USD, EnumCoins.HKD)),
  USD_SAR(EnumCoins.descriptionFromCombinations(EnumCoins.USD, EnumCoins.SAR)),
  USD_INR(EnumCoins.descriptionFromCombinations(EnumCoins.USD, EnumCoins.INR)),
  USD_KRW(EnumCoins.descriptionFromCombinations(EnumCoins.USD, EnumCoins.KRW)),
  USD_ALL(EnumCoins.descriptionFromCombinations(EnumCoins.USD, EnumCoins.ALL)),
  USD_AMD(EnumCoins.descriptionFromCombinations(EnumCoins.USD, EnumCoins.AMD)),
  USD_ANG(EnumCoins.descriptionFromCombinations(EnumCoins.USD, EnumCoins.ANG)),
  USD_ARS(EnumCoins.descriptionFromCombinations(EnumCoins.USD, EnumCoins.ARS)),
  USD_AUD(EnumCoins.descriptionFromCombinations(EnumCoins.USD, EnumCoins.AUD)),
  USD_BBD(EnumCoins.descriptionFromCombinations(EnumCoins.USD, EnumCoins.BBD)),
  USD_BDT(EnumCoins.descriptionFromCombinations(EnumCoins.USD, EnumCoins.BDT)),
  USD_BGN(EnumCoins.descriptionFromCombinations(EnumCoins.USD, EnumCoins.BGN)),
  USD_BHD(EnumCoins.descriptionFromCombinations(EnumCoins.USD, EnumCoins.BHD)),
  USD_BIF(EnumCoins.descriptionFromCombinations(EnumCoins.USD, EnumCoins.BIF)),
  USD_BND(EnumCoins.descriptionFromCombinations(EnumCoins.USD, EnumCoins.BND)),
  USD_BOB(EnumCoins.descriptionFromCombinations(EnumCoins.USD, EnumCoins.BOB)),
  USD_BSD(EnumCoins.descriptionFromCombinations(EnumCoins.USD, EnumCoins.BSD)),
  USD_BWP(EnumCoins.descriptionFromCombinations(EnumCoins.USD, EnumCoins.BWP)),
  USD_BZD(EnumCoins.descriptionFromCombinations(EnumCoins.USD, EnumCoins.BZD)),
  USD_CLP(EnumCoins.descriptionFromCombinations(EnumCoins.USD, EnumCoins.CLP)),
  USD_CNY(EnumCoins.descriptionFromCombinations(EnumCoins.USD, EnumCoins.CNY)),
  USD_COP(EnumCoins.descriptionFromCombinations(EnumCoins.USD, EnumCoins.COP)),
  USD_CRC(EnumCoins.descriptionFromCombinations(EnumCoins.USD, EnumCoins.CRC)),
  USD_CUP(EnumCoins.descriptionFromCombinations(EnumCoins.USD, EnumCoins.CUP)),
  USD_DJF(EnumCoins.descriptionFromCombinations(EnumCoins.USD, EnumCoins.DJF)),
  USD_DOP(EnumCoins.descriptionFromCombinations(EnumCoins.USD, EnumCoins.DOP)),
  USD_DZD(EnumCoins.descriptionFromCombinations(EnumCoins.USD, EnumCoins.DZD)),
  USD_EGP(EnumCoins.descriptionFromCombinations(EnumCoins.USD, EnumCoins.EGP)),
  USD_ETB(EnumCoins.descriptionFromCombinations(EnumCoins.USD, EnumCoins.ETB)),
  USD_FJD(EnumCoins.descriptionFromCombinations(EnumCoins.USD, EnumCoins.FJD)),
  USD_GBP(EnumCoins.descriptionFromCombinations(EnumCoins.USD, EnumCoins.GBP)),
  USD_GEL(EnumCoins.descriptionFromCombinations(EnumCoins.USD, EnumCoins.GEL)),
  USD_GHS(EnumCoins.descriptionFromCombinations(EnumCoins.USD, EnumCoins.GHS)),
  USD_GMD(EnumCoins.descriptionFromCombinations(EnumCoins.USD, EnumCoins.GMD)),
  USD_GNF(EnumCoins.descriptionFromCombinations(EnumCoins.USD, EnumCoins.GNF)),
  USD_GTQ(EnumCoins.descriptionFromCombinations(EnumCoins.USD, EnumCoins.GTQ)),
  USD_HNL(EnumCoins.descriptionFromCombinations(EnumCoins.USD, EnumCoins.HNL)),
  USD_HRK(EnumCoins.descriptionFromCombinations(EnumCoins.USD, EnumCoins.HRK)),
  USD_HTG(EnumCoins.descriptionFromCombinations(EnumCoins.USD, EnumCoins.HTG)),
  USD_IDR(EnumCoins.descriptionFromCombinations(EnumCoins.USD, EnumCoins.IDR)),
  USD_IQD(EnumCoins.descriptionFromCombinations(EnumCoins.USD, EnumCoins.IQD)),
  USD_IRR(EnumCoins.descriptionFromCombinations(EnumCoins.USD, EnumCoins.IRR)),
  USD_ISK(EnumCoins.descriptionFromCombinations(EnumCoins.USD, EnumCoins.ISK)),
  USD_JMD(EnumCoins.descriptionFromCombinations(EnumCoins.USD, EnumCoins.JMD)),
  USD_KES(EnumCoins.descriptionFromCombinations(EnumCoins.USD, EnumCoins.KES)),
  USD_KHR(EnumCoins.descriptionFromCombinations(EnumCoins.USD, EnumCoins.KHR)),
  USD_KMF(EnumCoins.descriptionFromCombinations(EnumCoins.USD, EnumCoins.KMF)),
  USD_KZT(EnumCoins.descriptionFromCombinations(EnumCoins.USD, EnumCoins.KZT)),
  USD_LAK(EnumCoins.descriptionFromCombinations(EnumCoins.USD, EnumCoins.LAK)),
  USD_LBP(EnumCoins.descriptionFromCombinations(EnumCoins.USD, EnumCoins.LBP)),
  USD_LKR(EnumCoins.descriptionFromCombinations(EnumCoins.USD, EnumCoins.LKR)),
  USD_LSL(EnumCoins.descriptionFromCombinations(EnumCoins.USD, EnumCoins.LSL)),
  USD_LYD(EnumCoins.descriptionFromCombinations(EnumCoins.USD, EnumCoins.LYD)),
  USD_MAD(EnumCoins.descriptionFromCombinations(EnumCoins.USD, EnumCoins.MAD)),
  USD_MDL(EnumCoins.descriptionFromCombinations(EnumCoins.USD, EnumCoins.MDL)),
  USD_MGA(EnumCoins.descriptionFromCombinations(EnumCoins.USD, EnumCoins.MGA)),
  USD_MKD(EnumCoins.descriptionFromCombinations(EnumCoins.USD, EnumCoins.MKD)),
  USD_MMK(EnumCoins.descriptionFromCombinations(EnumCoins.USD, EnumCoins.MMK)),
  USD_MOP(EnumCoins.descriptionFromCombinations(EnumCoins.USD, EnumCoins.MOP)),
  USD_MRO(EnumCoins.descriptionFromCombinations(EnumCoins.USD, EnumCoins.MRO)),
  USD_MUR(EnumCoins.descriptionFromCombinations(EnumCoins.USD, EnumCoins.MUR)),
  USD_MVR(EnumCoins.descriptionFromCombinations(EnumCoins.USD, EnumCoins.MVR)),
  USD_MWK(EnumCoins.descriptionFromCombinations(EnumCoins.USD, EnumCoins.MWK)),
  USD_MYR(EnumCoins.descriptionFromCombinations(EnumCoins.USD, EnumCoins.MYR)),
  USD_NAD(EnumCoins.descriptionFromCombinations(EnumCoins.USD, EnumCoins.NAD)),
  USD_NGN(EnumCoins.descriptionFromCombinations(EnumCoins.USD, EnumCoins.NGN)),
  USD_NIO(EnumCoins.descriptionFromCombinations(EnumCoins.USD, EnumCoins.NIO)),
  USD_NPR(EnumCoins.descriptionFromCombinations(EnumCoins.USD, EnumCoins.NPR)),
  USD_NZD(EnumCoins.descriptionFromCombinations(EnumCoins.USD, EnumCoins.NZD)),
  USD_OMR(EnumCoins.descriptionFromCombinations(EnumCoins.USD, EnumCoins.OMR)),
  USD_PAB(EnumCoins.descriptionFromCombinations(EnumCoins.USD, EnumCoins.PAB)),
  USD_PEN(EnumCoins.descriptionFromCombinations(EnumCoins.USD, EnumCoins.PEN)),
  USD_PGK(EnumCoins.descriptionFromCombinations(EnumCoins.USD, EnumCoins.PGK)),
  USD_PHP(EnumCoins.descriptionFromCombinations(EnumCoins.USD, EnumCoins.PHP)),
  USD_PKR(EnumCoins.descriptionFromCombinations(EnumCoins.USD, EnumCoins.PKR)),
  USD_PYG(EnumCoins.descriptionFromCombinations(EnumCoins.USD, EnumCoins.PYG)),
  USD_QAR(EnumCoins.descriptionFromCombinations(EnumCoins.USD, EnumCoins.QAR)),
  USD_RON(EnumCoins.descriptionFromCombinations(EnumCoins.USD, EnumCoins.RON)),
  USD_RSD(EnumCoins.descriptionFromCombinations(EnumCoins.USD, EnumCoins.RSD)),
  USD_RWF(EnumCoins.descriptionFromCombinations(EnumCoins.USD, EnumCoins.RWF)),
  USD_SCR(EnumCoins.descriptionFromCombinations(EnumCoins.USD, EnumCoins.SCR)),
  USD_SDG(EnumCoins.descriptionFromCombinations(EnumCoins.USD, EnumCoins.SDG)),
  USD_SOS(EnumCoins.descriptionFromCombinations(EnumCoins.USD, EnumCoins.SOS)),
  USD_STD(EnumCoins.descriptionFromCombinations(EnumCoins.USD, EnumCoins.STD)),
  USD_SVC(EnumCoins.descriptionFromCombinations(EnumCoins.USD, EnumCoins.SVC)),
  USD_SYP(EnumCoins.descriptionFromCombinations(EnumCoins.USD, EnumCoins.SYP)),
  USD_SZL(EnumCoins.descriptionFromCombinations(EnumCoins.USD, EnumCoins.SZL)),
  USD_TND(EnumCoins.descriptionFromCombinations(EnumCoins.USD, EnumCoins.TND)),
  USD_TTD(EnumCoins.descriptionFromCombinations(EnumCoins.USD, EnumCoins.TTD)),
  USD_TWD(EnumCoins.descriptionFromCombinations(EnumCoins.USD, EnumCoins.TWD)),
  USD_TZS(EnumCoins.descriptionFromCombinations(EnumCoins.USD, EnumCoins.TZS)),
  USD_UAH(EnumCoins.descriptionFromCombinations(EnumCoins.USD, EnumCoins.UAH)),
  USD_UGX(EnumCoins.descriptionFromCombinations(EnumCoins.USD, EnumCoins.UGX)),
  USD_UYU(EnumCoins.descriptionFromCombinations(EnumCoins.USD, EnumCoins.UYU)),
  USD_UZS(EnumCoins.descriptionFromCombinations(EnumCoins.USD, EnumCoins.UZS)),
  USD_VEF(EnumCoins.descriptionFromCombinations(EnumCoins.USD, EnumCoins.VEF)),
  USD_VND(EnumCoins.descriptionFromCombinations(EnumCoins.USD, EnumCoins.VND)),
  USD_VUV(EnumCoins.descriptionFromCombinations(EnumCoins.USD, EnumCoins.VUV)),
  USD_XAF(EnumCoins.descriptionFromCombinations(EnumCoins.USD, EnumCoins.XAF)),
  USD_XCD(EnumCoins.descriptionFromCombinations(EnumCoins.USD, EnumCoins.XCD)),
  USD_XOF(EnumCoins.descriptionFromCombinations(EnumCoins.USD, EnumCoins.XOF)),
  USD_XPF(EnumCoins.descriptionFromCombinations(EnumCoins.USD, EnumCoins.XPF)),
  USD_YER(EnumCoins.descriptionFromCombinations(EnumCoins.USD, EnumCoins.YER)),
  USD_ZMK(EnumCoins.descriptionFromCombinations(EnumCoins.USD, EnumCoins.ZMK)),
  USD_BYN(EnumCoins.descriptionFromCombinations(EnumCoins.USD, EnumCoins.BYN)),
  USD_AZN(EnumCoins.descriptionFromCombinations(EnumCoins.USD, EnumCoins.AZN)),
  USD_CNH(EnumCoins.descriptionFromCombinations(EnumCoins.USD, EnumCoins.CNH)),
  USD_KGS(EnumCoins.descriptionFromCombinations(EnumCoins.USD, EnumCoins.KGS)),
  USD_TJS(EnumCoins.descriptionFromCombinations(EnumCoins.USD, EnumCoins.TJS)),
  USD_AOA(EnumCoins.descriptionFromCombinations(EnumCoins.USD, EnumCoins.AOA)),
  USD_TMT(EnumCoins.descriptionFromCombinations(EnumCoins.USD, EnumCoins.TMT)),
  USD_MNT(EnumCoins.descriptionFromCombinations(EnumCoins.USD, EnumCoins.MNT)),
  USD_AFN(EnumCoins.descriptionFromCombinations(EnumCoins.USD, EnumCoins.AFN)),

  USD_EUR(EnumCoins.descriptionFromCombinations(EnumCoins.USD, EnumCoins.EUR)),
  //endregion
  // region V
  VEF_BRL(EnumCoins.descriptionFromCombinations(EnumCoins.VEF, EnumCoins.BRL)),
  VEF_EUR(EnumCoins.descriptionFromCombinations(EnumCoins.VEF, EnumCoins.EUR)),
  VEF_USD(EnumCoins.descriptionFromCombinations(EnumCoins.VEF, EnumCoins.USD)),
  VND_USD(EnumCoins.descriptionFromCombinations(EnumCoins.VND, EnumCoins.USD)),
  //endregion
  // region X
  XAGG_EUR(EnumCoins.descriptionFromCombinations(EnumCoins.XAGG, EnumCoins.EUR)),
  XAGG_USD(EnumCoins.descriptionFromCombinations(EnumCoins.XAGG, EnumCoins.USD)),
  XBR_USD(EnumCoins.descriptionFromCombinations(EnumCoins.XBR, EnumCoins.USD)),
  XRP_BRL(EnumCoins.descriptionFromCombinations(EnumCoins.XRP, EnumCoins.BRL)),
  XRP_EUR(EnumCoins.descriptionFromCombinations(EnumCoins.XRP, EnumCoins.EUR)),
  XRP_USD(EnumCoins.descriptionFromCombinations(EnumCoins.XRP, EnumCoins.USD)),
  //endregion
  // region Z
  ZAR_EUR(EnumCoins.descriptionFromCombinations(EnumCoins.ZAR, EnumCoins.EUR)),
  ZAR_BRL(EnumCoins.descriptionFromCombinations(EnumCoins.ZAR, EnumCoins.BRL)),
  ZAR_USD(EnumCoins.descriptionFromCombinations(EnumCoins.ZAR, EnumCoins.USD));
  //endregion
  
  private final String description;

  EnumCombinations(String description) {
    this.description = description;
  }

  public String getDescription() {
    return this.description;
  }

  public String toString() {
    return this.name().replace("_", "-");
  }
}
